version: '2'

services:
  mongodb:
    image: mongo:5.0.25-focal
    container_name: c_mongodb
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
    ports:
      - "27017:27017"
    command: mongod
    networks:
      - mynetwork

  logservice1:
    image: tianrojas/roundrobinbd:latest
    container_name: logservice1
    ports:
      - "34001:34000"
    networks:
      - mynetwork

  logservice2:
    image: tianrojas/roundrobinbd:latest
    container_name: logservice2
    ports:
      - "34002:34000"
    networks:
      - mynetwork

  logservice3:
    image: tianrojas/roundrobinbd:latest
    container_name: logservice3
    ports:
      - "34003:34000"
    networks:
      - mynetwork

  logroundrobin:
    image: logroundrobin:latest
    container_name: logroundrobin
    ports:
      - "35000:34000"    
    networks:
      - mynetwork

volumes:
  mongodb:
  mongodb_config:

networks:
  mynetwork:
    driver: bridge
    external: true
